book/urls.py
    
from django.urls import path
from .views import (BookDetailView,
    CheckoutView,
    HomeView,
    add_book_to_cart,
    remove_book_from_cart,
    remove_one_book_from_cart,
    OrderFinalView,
    PaymentView,
    category_filter_selector
    
)

app_name = 'book'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('category_filter/<cat>/', category_filter_selector, name='category_filter'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order_final_view/', OrderFinalView.as_view(), name='order_final_view'),
    path('book_detail/<slug>/', BookDetailView.as_view(), name='book_detail'),
    path('add_book_to_cart/<slug>/', add_book_to_cart, name='add_book_to_cart'),
    path('remove_book_from_cart/<slug>/', remove_book_from_cart, name='remove_book_from_cart'),
    path('remove_one_book_from_cart/<slug>/', remove_one_book_from_cart, name='remove_one_book_from_cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
]

ink_dream/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from profiles.views import profile_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('account/profile/', profile_view, name='profile'),
    path('', include('book.urls', namespace='book')),
    path('', include('search.urls', namespace='search')),
    path('', include('contact.urls', namespace='contact')),
    
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from django_countries.fields import CountryField

# Book model all the properties

GENGRE_ELECTION  = (
  ('FT','Fairy Tale'),
  ('BA','Biography'),
  ('CL','Classic'),
  ('RO','Romance'),
  ('AA','Action and Adventure'),
  ('CD','Crime and Detective'),
  ('CN','Comic and Graphic Novel'),
  ('HI','Historical Fiction'),
  ('MY','Mythology'),
  ('ST','Suspense-Thriller'),
  ('SF','Science Fiction'),
  ('F','Fantasy'),
  ('P','Poetry'),
  ('S','Satire'),
  ('E','Essay'),
)

STICKER_CHOICES = (
  ('P','primary'),
  ('Se','secondary'),
  ('S','success'),
  ('D','danger'),
  ('I','info'),
  ('W','warning'),
  ('DE','default')
)
    
class Book(models.Model):
    title = models.CharField(max_length=100)
    work_author = models.CharField(max_length=100)    
    cover = models.ImageField()
    discount_price = models.FloatField(blank=True, null=True)
    price = models.FloatField()
    category = models.CharField(choices=GENGRE_ELECTION, max_length=2)
    sticker = models.CharField(choices=STICKER_CHOICES, max_length=2, blank=True, null=True)
    slug= models.SlugField()
    publish_date = models.DateTimeField()
    description = models.TextField()    
    bestseller = models.BooleanField(default=False)
    notbestseller = models.BooleanField(default=False)
    longbook = models.BooleanField(default=False)
    shortbook = models.BooleanField(default=False)
    worldwide_appreciated = models.BooleanField(default=False)
    underground_appreciation = models.BooleanField(default=False)
    

    def __str__(self):
        return self.title
    
    def get_choices(self):
        category_choices = []
        for category in GENGRE_ELECTION:
            category_choices.append(category[1])
        return category_choices
      
    def get_absolute_url(self):
        return reverse("book:book_detail", kwargs={'slug': self.slug})
      
    def get_add_book_to_cart_url(self):
        return reverse("book:add_book_to_cart", kwargs={'slug': self.slug})
    
    def get_remove_book_from_cart(self):
        return reverse("book:remove_book_from_cart", kwargs={'slug': self.slug})    
      

# Model for the Order Sumary

class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Book, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"
    
    def get_total_item_price(self): 
        return self.quantity * self.item.price
    
    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price
    
    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()

#Book oreder Check out form before saving
class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey(
        'SaveCustomerAddress', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.user.username
    
    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total
    
#Book check out form         
    
class SaveCustomerAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    house_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username
    
#Stripe payment form    
class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username       

profiles/models.py
from django.db import models

# Create your models here.

profiles/views.py
from django.shortcuts import render
from book.models import Order

def profile_view(request):
  orders = Order.objects.filter(user=request.user, ordered=True)
  context = {
    'orders': orders
  }
  return render(request, "profile.html", context )

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  {% comment %} <link href="{% static 'css/style.min.css' %}" rel="stylesheet"> {% endcomment %}
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link href="{% static 'css/payment.css' %}" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Dancing+Script&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Redressed&display=swap" rel="stylesheet"> 
</head>

{% include "navbar.html" %}

<body>
  <!--Django messages-->
  <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
  </div>

    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}

    {% include "footer.html" %}
    {% include "scripts.html" %}
</body>
</html>

templates/book_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">
      <div class="row wow fadeIn">
      <!--Book image column-->
        <div class="col-md-6 mb-4">
          <img class="card-img-top h-100" src="{{ object.cover.url }}" alt="">   
        </div>
      <div class="col-md-6 mb-4">
        <div class="p-4">
        <!--Book data and categories-->
          <div class="mb-2">
            <h1 class=" brown-text detail-title text-center bold">{{ object.title }}</h1>
          <hr>
          <!--Book author & other informative tags-->
            <h4><span class="badge badge-light ">{{ object.work_author }}</span></h4>
            <span class="badge badge-pill purple ">{{ object.publish_date }}</span>
            <span class="badge badge-pill {{ object.get_sticker_display }}-color ">{{ object.get_category_display }}</span>
            <span class="badge badge-pill indigo"  >{{ object.slug }}</span>
          <hr>  
          
          <!--Book description-->  
          <p class="lead font-weight "><u>Description</u></p>
          <p>{{ object.description }}</p>
        <hr>

          <!--Book price and discount prices-->
          <h1>Price <span class="badge badge-light">
            
            {% if object.discount_price %}
              <span class="badge badge-danger">
                <del >{{ object.price }} €</del>
              </span>
              <span class="badge badge-success">{{ object.discount_price }} €</span>
              {% else %}
              <span class="badge badge-success">{{ object.price }} €</span>
              {% endif %}
            </h1>
            <hr>  
            
          </div>
          <!--buttons add/remove-->  
            <a href="{{ object.get_add_book_to_cart_url }}" class="btn btn-primary btn-md my-1 p text-center">Add to cart
            <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href="{{ object.get_remove_book_from_cart }}" class="btn btn-danger btn-md my-1 p text-center">Eliminate from cart
            <i class="fas fa-backspace ml-1"></i></a>
        </div>
      </div>
    </div>
    <hr>
    <!--Additional information-->
      <div class="row d-flex justify-content-center wow fadeIn">
        <div class="col-md-6 text-center">
          <h4 class="my-4 h4">Additional information</h4>
          <p>Here you can check some extra info that we wish it will bring you in one of our inked fulled dreams. Enjoy the book no matter what the people say, or how short it is, the ost important is your will to discover</p>
        </div>
      </div>
      <div class="row wow fadeIn">
        <div class="col-lg-4 mb-4 col-md-6 text-center">
          <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTT6ycgIFx0AKQTUcBK98hHyyDNm3AApcNPSo4ANGettOoT0MSO" class="img-fluid" alt="">
          <ul class="list-group">  
            <label>   
          <li class="list-group-item">{% if object.bestseller %}             
              <input name="bestseller" id="bestseller" type="checkbox" class="filled-in" checked="checked" />
          {% else %}
              <input name="bestseller" id="bestseller" type="checkbox" class="filled-in"  />
          {% endif %}
              <span>bestseller</span></li>
              </label> 
          <label>
          <li class="list-group-item">{% if object.notbestseller %}             
              <input name="notbestseller" id="notbestseller" type="checkbox" class="filled-in" checked="checked" />
          {% else %}
              <input name="notbestseller" id="notbestseller" type="checkbox" class="filled-in"  />
          {% endif %}
              <span>notbestseller</span></li>
              </label>
          </ul>    
        </div>
        
      <div class="col-lg-4 mb-4 col-md-6 text-center">
          <img src="http://i2.wp.com/clipartportal.com/wp-content/uploads/2018/12/thick-and-thin-clipart.jpg" class="img-fluid" alt="">
          <ul class="list-group">  
            <label>   
          <li class="list-group-item">{% if object.longbook %}             
              <input name="bestseller" id="bestseller" type="checkbox" class="filled-in" checked="checked" />
          {% else %}
              <input name="bestseller" id="bestseller" type="checkbox" class="filled-in"  />
          {% endif %}
              <span>longbook</span></li>
              </label> 
          <label>
          <li class="list-group-item">{% if object.shortbook %}             
              <input name="notbestseller" id="notbestseller" type="checkbox" class="filled-in" checked="checked" />
          {% else %}
              <input name="notbestseller" id="notbestseller" type="checkbox" class="filled-in"  />
          {% endif %}
              <span>shortbook</span></li>
              </label>
          </ul>    
        </div>
        <div class="col-lg-4 mb-4 col-md-6 text-center">
          <img src="https://zvw-shop.de/media/image/c9/94/8d/Banner-02-Startseite-575x380-2x2-books58d92b27dbd21_800x800.jpg" class="img-fluid" alt="">
          <ul class="list-group">  
            <label>   
          <li class="list-group-item">{% if object.worldwide_appreciated %}             
              <input name="bestseller" id="bestseller" type="checkbox" class="filled-in" checked="checked" />
          {% else %}
              <input name="bestseller" id="bestseller" type="checkbox" class="filled-in"  />
          {% endif %}
              <span>worldwide_appreciated</span></li>
              </label> 
          <label>
          <li class="list-group-item">{% if object.underground_appreciation %}             
              <input name="notbestseller" id="notbestseller" type="checkbox" class="filled-in" checked="checked" />
          {% else %}
              <input name="notbestseller" id="notbestseller" type="checkbox" class="filled-in"  />
          {% endif %}
              <span>underground_appreciation</span></li>
              </label>
          </ul>    
        </div>
      </div>
    </div>
  </main>
{% endblock content %}

templates/checkout.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main >
    <div class="container wow fadeIn">
      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout form</h2>
      <div class="row">
        <div class="col-md-8 mb-4">
          <div class="card">
            <form method="POST" class="card-body">
              {% csrf_token %}
              <!--address-->
              <div class="md-form mb-5">
                {{ form.street_address }}
                <label for="address" class="">Address</label>
              </div>
              <!--address-2-->
              <div class="md-form mb-5">
                {{ form.house_address }}
                <label for="address-2" class="">Address 2 (optional)</label>
              </div>
              <!--django country selector-->
              <div class="row">
                <div class="col-lg-4 col-md-12 mb-4">
                  <label for="country">Country</label>
                  {{ form.country }}
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>
                </div>
                <!--Zip code-->
                <div class="col-lg-4 col-md-6 mb-4">
                <label for="zip">Zip</label>
                  {{ form.zip }}
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>
                </div>
              </div>
            <hr>
              <div class="d-block my-3">
                {% for value, name in form.fields.payment_option.choices %}
                <div class="custom-control custom-radio">
                  <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                </div>
                {% endfor %}
              </div>
              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>
            </form>
          </div>
        </div>
        <!--Grid column total aside-->
        <div class="col-md-4 mb-4">
          {% include "total_order_page.html" %}
        </div>
      </div>
    </div>
  </main>
{% endblock content %}

templates/home.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<title>Books list</title>
  <!--Carousel Wrapper-->
<div id="carousel-example-2" class="carousel slide carousel-fade" data-ride="carousel">
  <!--Indicators-->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-2" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-2" data-slide-to="1"></li>
    <li data-target="#carousel-example-2" data-slide-to="2"></li>
  </ol>
  <!--/.Indicators-->
  <!--Slides-->
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <div class="view">
        <img class="d-block w-100" src="https://i.pinimg.com/originals/34/89/eb/3489eba220a57ca8188dfeb319f28ed7.jpg"
          alt="First slide">
        <div class="mask rgba-black-light"></div>
      </div>
      <div class="carousel-caption">
        <h3 class="h3-responsive"><strong>"Some books are tested, others devoured, very few are chewed and digested."</strong></h3>
        <p><strong>Sir Francis Bacon </strong></p>
      </div>
    </div>
    <div class="carousel-item">
      <!--Mask color-->
      <div class="view">
        <img class="d-block w-100" src="https://elvasnews.pt/blog/wp-content/uploads/2015/12/Semin%C3%A1rio-Livro-Antigo.jpg"
          alt="Second slide">
        <div class="mask rgba-black-strong"></div>
      </div>
      <div class="carousel-caption">
        <h3 class="h3-responsive"><strong>"He who reads a lot and walks a lot, sees a lot and knows a lot ”</strong></h3>
        <p><strong>Miguel de Cervantes</strong></p>
      </div>
    </div>
    <div class="carousel-item">
      <!--Mask color-->
      <div class="view">
        <img class="d-block w-100" src="https://motaen.com/upload/wallpapers/source/2013/07/13/12/01/36650/c4mtQ6Qf4G.jpg"
          alt="Third slide">
        <div class="mask rgba-black-slight"></div>
      </div>
      <div class="carousel-caption">
        <h3 class="h3-responsive"><strong>"Reading is like an art. It took me eighty years and I can not say I'm here yet."</strong></h3>
        <p><strong>Johann Wolfgang von Goethe</strong></p>
      </div>
    </div>
  </div>
  <!--/.Slides-->
  <!--Controls-->
  <a class="carousel-control-prev" href="#carousel-example-2" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carousel-example-2" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  <!--/.Controls-->
</div>
<!--/.Carousel Wrapper-->
  <main>
  <!--Navbar-->
  <div class="container">
    <nav class="navbar navbar-expand-lg navbar-light indigo darken-3 mb-4 mt-3 mb-5">
    <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <form class="form-inline">
          <span class="input-group-append">
            <div class="input-group-text bg-transparent">
                <i class="fa fa-search"></i>
            </div>
          </span>
          <input class="form-control py-2 border-right-0 border" type="search" name="title_contains" placeholder="Title contains...">
        </form>
        <a class="undo" href="/" role="button">&nbsp;<i class="fas fa-undo"></i></a> 
      </div>
      <!-- advanced serching -->
        <a class='button btn btn-mdb-color blue lighten-3' href='search/SearchFilters_BookView/' <i class="far fa-hand-point-right" aria-hidden="true"></i> &nbsp; Advanced searching
        </a> 
    </nav>
    
    <!--/.Navbar-->
      <!--Section: Products (books)-->
      <section class="text-center mb-4">
        <div class="row wow fadeIn">
          {% for item in object_list %}
            <div class="col-lg-3 col-md-6 mb-4">
            <div class="card" style="height: 540px;">
              <div class="view overlay zoom">
              <!--book image-->
                <a href="{{ item.cover.url }}">
                  <img class="card-img-top" src="{{ item.cover.url }}" alt="">
                </a>
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                  <div class="mask flex-center"><p class="white-text">to be opened</p></div>
                </a>
              </div>
                <h5>
                  <strong><a href="{{ item.get_absolute_url }}" class="brown-text">{{ item.title }}</a></strong>
                </h5>
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="{{ item.get_absolute_url }}" class="grey-text">
                  <h6>{{ item.get_category_display }} </h6>
                </a>
                <a href="{{ item.get_absolute_url }}" class="dark-grey-text">
                  {{ item.work_author }}
                </a>
                <h3>
                  <div class="card-footer">
                    <strong> 
                    {% if item.discount_price %}
                  <h6 class="badge badge-light">
                  <span class="badge badge-danger">
                    <del>{{ item.price }} €</del>
                  </span>
                  <span class="badge badge-success"><u>{{ item.discount_price }} €</u></span></h6>
                    {% else %}
                  <span class="badge badge-success">{{ item.price }} €</span>
                    {% endif %}
                    </strong>
                  </div>
                </h3>  
              </div>
            </div>
        </div>
          {% endfor %}  
        </div>
      </section>
      <!--Pagination-->
      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}
          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>
          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
    {% endif %}  
    </div>
  </main>
{% endblock content %}

templates/navbar.html
{% load trolley_template_tags %}
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">
      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="/">
        <strong class="blue-text"><i class="fas fa-tint"></i> Ink Dream </strong>
      </a>
      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <!--Contact-->
          <li class="nav-item navbar_text">      
      <a class="nav-link waves-effect" href='/contact/ContactFormView/' target="_blank"><i class="fas fa-file-signature"></i> <u>Contact us</u></a>
          </li>
        </ul>
          <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item navbar_text">
            <a href="{% url 'book:order_final_view' %}" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{request.user|tolley_item_count }}  </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          <li class="nav-item navbar_text">
            <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
              <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>
          <li class="nav-item navbar_text">
            <a class="nav-link" href="{% url 'profile' %}">Account</a>  
          </li>
          {% else %}
          <li class="nav-item navbar_text">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}">
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
          <li class="nav-item navbar_text">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
              <span class="clearfix d-none d-sm-inline-block"> Signup </span>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>

    </div>
  </nav>

templates/order_final_view.html
{% extends "base.html" %}
{% block content %}
<!--Order records per user-->
  <main>
    <div class="container">
        <div class="table-responsive text-nowrap">
            <h2>Order Summary</h2>
            <!-- Collumns headers -->
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Book title</th>
                    <th scope="col">Price</th>
                    <th scope="col">Amonut</th>
                    <th scope="col">Total Amonut</th>
                </tr>
                </thead>
                <tbody>
                <!-- Collumns content -->
                {% for order_item in object.items.all %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ order_item.item.title }}</td>
                    <td>{{ order_item.item.price }}</td>
                    <td>
                        <a href="{% url 'book:remove_one_book_from_cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                        {{ order_item.quantity }}
                        <a href="{% url 'book:add_book_to_cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
                    </td>
                    <td>
                    {% if order_item.item.discount_price %}
                        € {{ order_item.get_total_discount_item_price }}
                        <span class="badge badge-primary">Saving $€{{ order_item.get_amount_saved }}</span>
                    {% else %}
                        € {{ order_item.get_total_item_price }}
                    {% endif %}
                    <a style='color: red;' href="{% url 'book:remove_book_from_cart' order_item.item.slug %}">
                        <i class="fas fa-trash float-right"></i>
                    </a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan='5'>Your cart is empty</td>
                </tr>
                <tr>
                    <td colspan="5">
                    <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
                    </td>
                </tr>
                {% endfor %}
                {% if object.get_total %}
                <tr>
                    <td colspan="4"><b>Order Total</b></td>
                    <td><b>${{ object.get_total }}</b></td>
                </tr>
                <tr>
                    <td colspan="5">
                    <a class='btn btn-warning float-right ml-2' href='/checkout/'>Proceed to checkout</a>
                    <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
                    </td>
                </tr>
                {% endif %}
                </tbody>
            </table>
        </div>
    </div>
  </main>
{% endblock content %}

templates/profile.html
{% extends "base.html" %}

{% block content %}
<main>
<div class="container main_content">
<h1 class="text-center">Customer existent orders </h1>
<hr />
  <table class=" table table-hover table-bordered text-center mb-4"">
      <tr class="text-center">
          <th>n°.</th>
          <th>User name</th>
          <th>Order date</th>
          <th>Adress</th>
          <th>Total</th>
      </tr>
      {% for order in orders %}
      <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ order.user }}</td>
          <td>{{ order.ordered_date }}</td>
          <td>{{ order.billing_address.street_address}}</td>
          <td>€{{ order.get_total }}</td>
      </tr>
      {% empty %}
      <tr>
      <td colspan="4">
          You haven´t yet purchased something from us...
      </td>
      </tr>
      {% endfor %}  
  </table>
</div>
</main>

{% endblock content %}